"""Initial migration: properties and features

Revision ID: 096c191c17a7
Revises: 
Create Date: 2026-01-25 11:45:53.330489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '096c191c17a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('property_id', sa.String(length=255), nullable=False),
    sa.Column('property_manager_host_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('market_area', sa.String(length=100), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('airbnb_host_url', sa.Text(), nullable=True),
    sa.Column('airbnb_listing_url', sa.Text(), nullable=True),
    sa.Column('vrbo_listing_url', sa.Text(), nullable=True),
    sa.Column('superhost', sa.Boolean(), nullable=False),
    sa.Column('is_guest_favorite', sa.Boolean(), nullable=False),
    sa.Column('minimum_stay', sa.Integer(), nullable=True),
    sa.Column('available_nights', sa.Integer(), nullable=True),
    sa.Column('occupancy', sa.Float(), nullable=True),
    sa.Column('instant_book', sa.Boolean(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('number_of_beds', sa.Integer(), nullable=True),
    sa.Column('accommodates', sa.Integer(), nullable=True),
    sa.Column('person_capacity', sa.Integer(), nullable=True),
    sa.Column('price_tier', sa.String(length=50), nullable=True),
    sa.Column('revenue', sa.Float(asdecimal=True), nullable=True),
    sa.Column('revenue_potential', sa.Float(asdecimal=True), nullable=True),
    sa.Column('adr', sa.Float(asdecimal=True), nullable=True),
    sa.Column('cleaning_fee', sa.Float(asdecimal=True), nullable=True),
    sa.Column('property_reviews', sa.Integer(), nullable=True),
    sa.Column('property_rating', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.Column('data_quality_category', sa.String(length=50), nullable=True),
    sa.Column('quality_rating_reason', sa.Text(), nullable=True),
    sa.Column('has_aircon', sa.Boolean(), nullable=False),
    sa.Column('has_gym', sa.Boolean(), nullable=False),
    sa.Column('has_hottub', sa.Boolean(), nullable=False),
    sa.Column('has_kitchen', sa.Boolean(), nullable=False),
    sa.Column('has_parking', sa.Boolean(), nullable=False),
    sa.Column('has_pets_allowed', sa.Boolean(), nullable=False),
    sa.Column('has_pool', sa.Boolean(), nullable=False),
    sa.Column('system_gym', sa.Boolean(), nullable=False),
    sa.Column('system_pool_table', sa.Boolean(), nullable=False),
    sa.Column('system_arcade_machine', sa.Boolean(), nullable=False),
    sa.Column('system_movie', sa.Boolean(), nullable=False),
    sa.Column('system_bowling', sa.Boolean(), nullable=False),
    sa.Column('system_chess', sa.Boolean(), nullable=False),
    sa.Column('system_golf', sa.Boolean(), nullable=False),
    sa.Column('system_crib', sa.Boolean(), nullable=False),
    sa.Column('system_pack_n_play', sa.Boolean(), nullable=False),
    sa.Column('system_play_slide', sa.Boolean(), nullable=False),
    sa.Column('system_firepit', sa.Boolean(), nullable=False),
    sa.Column('system_grill', sa.Boolean(), nullable=False),
    sa.Column('system_pool', sa.Boolean(), nullable=False),
    sa.Column('system_jacuzzi', sa.Boolean(), nullable=False),
    sa.Column('system_view_ocean', sa.Boolean(), nullable=False),
    sa.Column('system_view_mountain', sa.Boolean(), nullable=False),
    sa.Column('has_outdoor_furniture', sa.Boolean(), nullable=False),
    sa.Column('has_waterfront', sa.Boolean(), nullable=False),
    sa.Column('has_lake_access', sa.Boolean(), nullable=False),
    sa.Column('has_beach_access', sa.Boolean(), nullable=False),
    sa.Column('has_outdoor_dining_area', sa.Boolean(), nullable=False),
    sa.Column('high_season_insights', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_index(op.f('ix_properties_market_area'), 'properties', ['market_area'], unique=False)
    op.create_index(op.f('ix_properties_property_id'), 'properties', ['property_id'], unique=True)
    op.create_table('property_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=255), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('property_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=255), nullable=False),
    sa.Column('review_total_reviews', sa.Integer(), nullable=True),
    sa.Column('review_months_overall', sa.Integer(), nullable=True),
    sa.Column('review_months_with_reviews', sa.Integer(), nullable=True),
    sa.Column('review_months_without_reviews_overall', sa.Integer(), nullable=True),
    sa.Column('review_avg_reviews_per_month', sa.Float(), nullable=True),
    sa.Column('review_high_season_quarter', sa.Integer(), nullable=True),
    sa.Column('review_high_season_reviews', sa.Integer(), nullable=True),
    sa.Column('review_high_season_label', sa.String(length=50), nullable=True),
    sa.Column('review_count_stayed_with_kids', sa.Integer(), nullable=True),
    sa.Column('review_pct_stayed_with_kids', sa.Float(), nullable=True),
    sa.Column('review_count_group_trip', sa.Integer(), nullable=True),
    sa.Column('review_pct_group_trip', sa.Float(), nullable=True),
    sa.Column('review_count_stayed_with_a_pet', sa.Integer(), nullable=True),
    sa.Column('review_pct_stayed_with_a_pet', sa.Float(), nullable=True),
    sa.Column('review_missing_months_trailing_12', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_reviews')
    op.drop_table('property_amenities')
    op.drop_index(op.f('ix_properties_property_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_market_area'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
