"""add investment scores table

Revision ID: ad5c1dd036f8
Revises: 096c191c17a7
Create Date: 2026-01-26 00:29:06.503139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5c1dd036f8'
down_revision: Union[str, Sequence[str], None] = '096c191c17a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=255), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('investment_tier', sa.String(length=50), nullable=False),
    sa.Column('revenue_score', sa.Float(), nullable=False),
    sa.Column('occupancy_score', sa.Float(), nullable=False),
    sa.Column('positioning_score', sa.Float(), nullable=False),
    sa.Column('review_score', sa.Float(), nullable=False),
    sa.Column('amenity_score', sa.Float(), nullable=False),
    sa.Column('host_status_score', sa.Float(), nullable=False),
    sa.Column('seasonal_score', sa.Float(), nullable=False),
    sa.Column('market_area', sa.String(length=100), nullable=False),
    sa.Column('bedroom_count', sa.Integer(), nullable=True),
    sa.Column('revenue_vs_market_avg', sa.Float(), nullable=True),
    sa.Column('revenue_potential_gap', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_top_opportunity', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_scores_market_area'), 'investment_scores', ['market_area'], unique=False)
    op.create_index(op.f('ix_investment_scores_property_id'), 'investment_scores', ['property_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_scores_property_id'), table_name='investment_scores')
    op.drop_index(op.f('ix_investment_scores_market_area'), table_name='investment_scores')
    op.drop_table('investment_scores')
    # ### end Alembic commands ###
