"""add property indexes

Revision ID: cb4c122cc3e2
Revises: ad5c1dd036f8
Create Date: 2026-01-27 19:11:47.974112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4c122cc3e2'
down_revision: Union[str, Sequence[str], None] = 'ad5c1dd036f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_properties_analytics', 'properties', ['market_area', 'bedrooms', 'revenue', 'occupancy', 'adr'], unique=False, postgresql_where=sa.text('bedrooms IS NOT NULL AND revenue IS NOT NULL'), postgresql_using='btree')
    op.create_index('idx_properties_bedrooms', 'properties', ['bedrooms'], unique=False, postgresql_where=sa.text('bedrooms IS NOT NULL'), postgresql_using='btree')
    op.create_index('idx_properties_market_bedrooms_revenue', 'properties', ['market_area', 'bedrooms', 'revenue'], unique=False, postgresql_where=sa.text('bedrooms IS NOT NULL AND revenue IS NOT NULL'), postgresql_using='btree')
    op.create_index('idx_properties_revenue', 'properties', ['revenue'], unique=False, postgresql_where=sa.text('revenue IS NOT NULL'), postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_properties_revenue', table_name='properties', postgresql_where=sa.text('revenue IS NOT NULL'), postgresql_using='btree')
    op.drop_index('idx_properties_market_bedrooms_revenue', table_name='properties', postgresql_where=sa.text('bedrooms IS NOT NULL AND revenue IS NOT NULL'), postgresql_using='btree')
    op.drop_index('idx_properties_bedrooms', table_name='properties', postgresql_where=sa.text('bedrooms IS NOT NULL'), postgresql_using='btree')
    op.drop_index('idx_properties_analytics', table_name='properties', postgresql_where=sa.text('bedrooms IS NOT NULL AND revenue IS NOT NULL'), postgresql_using='btree')
    # ### end Alembic commands ###
